### ISSUE TITLE
Mariadb Latest doesn't work with Omeka 

### ISSUE THREAD

**Issue by kikeEsteban** [sunnypatel7/omeka-s-docker-image#1]
Adding new items fails with mariadb:latest image. 
To make it work, I had to change the docker-compose.yml  
`image: mariadb:latest`
to   
`image: mariadb:10.3.24 `

**Comment by sunnythepatel** [comment]
I think the issue could be with MariaDB: latest image if you want to feel free to PR and fix it. It will help others as well
